### ISSUE TITLE
Error occurred when running on cuda device

### ISSUE THREAD

**Issue by RoarBoil** [honeyhaoyan/python_version_Grid_GCN#1]
## when running on cuda 10.0 device this error occured, thank you for your help!
```
Traceback (most recent call last):
  File "train_cls.py", line 154, in <module>
    train(net, opt, scheduler, train_loader, dev)
  File "train_cls.py", line 76, in train
    logits = net(data)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baoyh/Grid-GCN/grid_gcn_final.py", line 572, in forward
    pos, feat = self.sa_module1(pos, feat, index_voxels, context_points, mask)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baoyh/Grid-GCN/grid_gcn_final.py", line 526, in forward
    g.update_all(self.message, self.conv)
  File "/home/anaconda3/lib/python3.6/site-packages/dgl/heterograph.py", line 4499, in update_all
    ndata = core.message_passing(g, message_func, reduce_func, apply_node_func)
  File "/home/anaconda3/lib/python3.6/site-packages/dgl/core.py", line 298, in message_passing
    ndata = invoke_udf_reduce(g, rfunc, msgdata, orig_nid=orig_nid)
  File "/home/anaconda3/lib/python3.6/site-packages/dgl/core.py", line 153, in invoke_udf_reduce
    retf.update_row(merged_nodes, merged_rst)
  File "/home/anaconda3/lib/python3.6/site-packages/dgl/frame.py", line 497, in update_row
    self._columns[key].update(rowids, val)
  File "/home/anaconda3/lib/python3.6/site-packages/dgl/frame.py", line 201, in update
    self.data = F.scatter_row(self.data, rowids, feats)
  File "/home/anaconda3/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py", line 190, in scatter_row
    return data.index_copy(0, row_index.long(), value)
IndexError: index_copy_(): Number of indices (16384) should be equal to source.size(dim) (32768)
```

**Comment by ShaneCN** [comment]
I have the same error, have you solved it?

**Comment by shenqildr** [comment]
I have met the same error
